PVSystem/PVSystem/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from User import views

urlpatterns = [
    url(r'^$', views.Index),
    url(r'^admin/', admin.site.urls),
    url(r'^SystemOwner/',include('SystemOwner.urls')),
    url(r'^User/',include('User.urls')),
]

PVSystem/SystemOwner/urls.py
from django.conf.urls import url
from SystemOwner import views

app_name = 'SystemOwner' #name = 'details' will be used along with app_name in views

urlpatterns = [
    url(r'^Details/$',views.OwnerView,name='Owner'),
    url(r'^EE/(?P<system_id>[0-9]+)/$',views.EE,name='EE'),
    url(r'^PE/(?P<system_id>[0-9]+)/$',views.PE,name='PE'),
    url(r'^Details/(?P<system_id>[0-9]+)/$',views.Details,name='Details'),
    url(r'^insert/$',views.InsertView,name='InsertView'),
    url(r'^EditView/$',views.EditView,name='EditView'),
    url(r'^EditProfile/$',views.EditProfile,name='EditProfile'),
    url(r'^insertPV/$',views.InsertPVView,name='InsertPVView'),
    url(r'^UploadXML/$',views.UploadXML,name='UploadXML'),
    url(r'^UploadXMLtoDB/$',views.UploadXMLtoDB,name='UploadXMLtoDB'),
    url(r'^DownloadResults(?P<system_id>[0-9]+)/$',views.DownloadResults,name='DownloadResults'),
    url(r'^CalculateEE/$',views.CalculateEE,name='CalculateEE'),
    url(r'^CompareResults/(?P<system_id>[0-9]+)/$',views.CompareResults,name='CompareResults'),
    url(r'^Logout/$',views.Logout,name='Logout'),
    url(r'^Delete/$',views.Delete,name='Delete'),
    url(r'^Update/$',views.Update,name='Update'),
    url(r'^UpdateAttempt/(?P<system_id>[0-9]+)/$',views.UpdateAttempt,name='UpdateAttempt'),
    url(r'^UpdateSystem/$',views.UpdateSystem,name='UpdateSystem'),
    url(r'^DeleteAttempt/(?P<system_id>[0-9]+)/$',views.DeleteAttempt,name='DeleteAttempt'),
    url(r'^GetLocation/$',views.getLocation,name='getLocation'),
    url(r'^ProvideAccess/$',views.ProvideAccess,name='ProvideAccess'),
    url(r'^UploadResultCSV/(?P<system_id>[0-9]+)/$',views.UploadResultCSV,name='UploadResultCSV'),
    url(r'^ActualE/$',views.ActualE,name='ActualE'),
    url(r'^LabView/$',views.LabView,name='LabView'),
]

PVSystem/User/urls.py
from django.conf.urls import url
from User import views

app_name = 'User' #name = 'details' will be used along with app_name in views

urlpatterns = [
    url(r'^Login/$',views.Login,name='Login'),
    url(r'^LoginAttempt/$',views.LoginAttempt,name='LoginAttempt'),
    url(r'^Register/$',views.Register,name='Register'),
    url(r'^RedirectSplash/$',views.RedirectSplash,name='RedirectSplash'),
    url(r'^RegisterUser/$',views.RegisterUser,name='RegisterUser'),
    url(r'^About/$',views.About,name='About'),
]

PVSystem/templates/CompareResults.html
<!DOCTYPE html>
{% load staticfiles %}
{% block body_block %}
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "css/AddNewPVSystem.css" %}">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="font-family:Verdana;color:#aaaaaa;">
	
<div class="header" >
	<h1><img class="himg" src="{% static "images/asu.png" %}">PV Module Performance Evaluation System</h1>
</div>

<div class="topnav">
	<a href="{% url 'SystemOwner:Logout' %}">Logout</a>
	<a href="{% url 'SystemOwner:EditView' %}">Edit Profile</a>
	<a href="/User/About/">About Us</a>
</div>
	
<div style="overflow:auto">
	<div class="menu">
    <div class="menuitem1">Menu</div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Owner' %}">Home</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:InsertView' %}">Add New PV System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Update' %}">Update System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Delete' %}">Delete PV System</a></div>
    <!--<div class="menuitem"><a class="a1" href="{% url 'SystemOwner:ProvideAccess' %}">Provide Access</a></div>-->
  	</div>
	<div>
		<h3>Results</h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>	Month	</th>
					<th>Predicted Energy (kWh)</th>
					<th>Expected Energy (kWh)</th>
					<th>Energy Ratio</th>
					
				</tr>
			</thead>
			<tbody>
			<tr>
				<td>January</td>
				<td>{{ key.0 }}</td>
				<td>{{ key.12 }}</td>
				<td>{{ key.24 }}</td>
			</tr>
			<tr>
				<td>February</td>
				<td>{{ key.1 }}</td>
				<td>{{ key.13 }}</td>
				<td>{{ key.25 }}</td>
			</tr>
			<tr>
				<td>March</td>
				<td>{{ key.2 }}</td>
				<td>{{ key.14 }}</td>
				<td>{{ key.26 }}</td>
			</tr>
			<tr>
				<td>April</td>
				<td>{{ key.3 }}</td>
				<td>{{ key.15 }}</td>
				<td>{{ key.27 }}</td>
			</tr>
			<tr>
				<td>May</td>
				<td>{{ key.4 }}</td>
				<td>{{ key.16 }}</td>
				<td>{{ key.28 }}</td>
			</tr>
			<tr>
				<td>June</td>
				<td>{{ key.5 }}</td>
				<td>{{ key.17 }}</td>
				<td>{{ key.29 }}</td>
			</tr>
			<tr>
				<td>July</td>
				<td>{{ key.6 }}</td>
				<td>{{ key.18 }}</td>
				<td>{{ key.30 }}</td>
			</tr>
			<tr>
				<td>August</td>
				<td>{{ key.7 }}</td>
				<td>{{ key.19 }}</td>
				<td>{{ key.31 }}</td>
			</tr>
			<tr>
				<td>September</td>
				<td>{{ key.8 }}</td>
				<td>{{ key.20 }}</td>
				<td>{{ key.32 }}</td>
			</tr>
			<tr>
				<td>October</td>
				<td>{{ key.9 }}</td>
				<td>{{ key.21 }}</td>
				<td>{{ key.33 }}</td>
			</tr>
			<tr>
				<td>November</td>
				<td>{{ key.10 }}</td>
				<td>{{ key.22 }}</td>
				<td>{{ key.34 }}</td>
			</tr>
			<tr>
				<td>December</td>
				<td>{{ key.11 }}</td>
				<td>{{ key.23 }}</td>
				<td>{{ key.35 }}</td>
			</tr>
			</tbody>
		</table>
		<br/><br/><br/>
		<!-- code for embeding graph-->
		
		<!--code for embeding graph ends here-->
		<h3><img class="himg2" src="{% static "images/comparisonrender.svg" %}"></h3>

		<button class="w3-button w3-green w3-small w3-round-large"><a class="a3" href="{% url 'SystemOwner:DownloadResults' key.36 %}">Download Results</a></button>

		<button class="w3-button w3-green w3-small w3-round-large>"><a class="a1" href="{% url 'SystemOwner:Owner' %}">Go Back</a></button>
	</div>
</div>
	</body>
</html>
{% endblock %}

PVSystem/templates/CompareResults2.html
<!DOCTYPE html>
{% load staticfiles %}
{% block body_block %}
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "css/AddNewPVSystem.css" %}">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="font-family:Verdana;color:#aaaaaa;">
	
<div class="header" >
	<h1><img class="himg" src="{% static "images/asu.png" %}">PV Module Performance Evaluation System</h1>
</div>

<div class="topnav">
	<a href="{% url 'SystemOwner:Logout' %}">Logout</a>
	<a href="{% url 'SystemOwner:EditView' %}">Edit Profile</a>
	<a href="/User/About/">About Us</a>
</div>
	
<div style="overflow:auto">
	<div class="menu">
    <div class="menuitem1">Menu</div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Owner' %}">Home</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:InsertView' %}">Add New PV System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Update' %}">Update System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Delete' %}">Delete PV System</a></div>
    <!--<div class="menuitem"><a class="a1" href="{% url 'SystemOwner:ProvideAccess' %}">Provide Access</a></div>-->
  	</div>
	<div>
		{% if key.49 == 1 %}
		<p style="text-align:center">Measured Energy Available! Download Results for Expected, Predicted and Measured Energies
		{% endif %}
		<h3>Results</h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>	Month	</th>
					<th>Predicted Energy (kWh)</th>
					<th>Expected Energy (kWh)</th>
					<th>Measured Energy (kWh)</th>
					<th>Energy Ratio</th>
					
				</tr>
			</thead>
			<tbody>
			<tr>
				<td>January</td>
				<td>{{ key.0 }}</td>
				<td>{{ key.12 }}</td>
				<td>{{ key.24 }}</td>
				<td>{{ key.36 }}</td>				
			</tr>
			<tr>
				<td>February</td>
				<td>{{ key.1 }}</td>
				<td>{{ key.13 }}</td>
				<td>{{ key.25 }}</td>
				<td>{{ key.37 }}</td>
			</tr>
			<tr>
				<td>March</td>
				<td>{{ key.2 }}</td>
				<td>{{ key.14 }}</td>
				<td>{{ key.26 }}</td>
				<td>{{ key.38 }}</td>
			</tr>
			<tr>
				<td>April</td>
				<td>{{ key.3 }}</td>
				<td>{{ key.15 }}</td>
				<td>{{ key.27 }}</td>
				<td>{{ key.39 }}</td>
			</tr>
			<tr>
				<td>May</td>
				<td>{{ key.4 }}</td>
				<td>{{ key.16 }}</td>
				<td>{{ key.28 }}</td>
				<td>{{ key.40 }}</td>
			</tr>
			<tr>
				<td>June</td>
				<td>{{ key.5 }}</td>
				<td>{{ key.17 }}</td>
				<td>{{ key.29 }}</td>
				<td>{{ key.41 }}</td>
			</tr>
			<tr>
				<td>July</td>
				<td>{{ key.6 }}</td>
				<td>{{ key.18 }}</td>
				<td>{{ key.30 }}</td>
				<td>{{ key.42 }}</td>
			</tr>
			<tr>
				<td>August</td>
				<td>{{ key.7 }}</td>
				<td>{{ key.19 }}</td>
				<td>{{ key.31 }}</td>
				<td>{{ key.43 }}</td>
			</tr>
			<tr>
				<td>September</td>
				<td>{{ key.8 }}</td>
				<td>{{ key.20 }}</td>
				<td>{{ key.32 }}</td>
				<td>{{ key.44 }}</td>
			</tr>
			<tr>
				<td>October</td>
				<td>{{ key.9 }}</td>
				<td>{{ key.21 }}</td>
				<td>{{ key.33 }}</td>
				<td>{{ key.45 }}</td>
			</tr>
			<tr>
				<td>November</td>
				<td>{{ key.10 }}</td>
				<td>{{ key.22 }}</td>
				<td>{{ key.34 }}</td>
				<td>{{ key.46 }}</td>
			</tr>
			<tr>
				<td>December</td>
				<td>{{ key.11 }}</td>
				<td>{{ key.23 }}</td>
				<td>{{ key.35 }}</td>
				<td>{{ key.47 }}</td>
			</tr>
			</tbody>
		</table>
		<br/><br/><br/>
		<!-- code for embeding graph-->
		
		<!--code for embeding graph ends here-->
		<h3><img class="himg2" src="{% static "images/comparisonrender.svg" %}"></h3>

		<button class="w3-button w3-green w3-small w3-round-large"><a class="a3" href="{% url 'SystemOwner:DownloadResults' key.48 %}">Download Results</a></button>

		<button class="w3-button w3-green w3-small w3-round-large>"><a class="a1" href="{% url 'SystemOwner:Owner' %}">Go Back</a></button>
	</div>
</div>
	</body>
</html>
{% endblock %}

PVSystem/templates/Lababoutus.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static "css/AddNewPVSystem.css" %}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="font-family:Verdana;color:#aaaaaa;">

<div class="header" >
  <h1><img class="himg" src="{% static "images/asu.png" %}">PV Module Performance Evaluation System</h1>
</div>

<div class="topnav">
  <a href="{% url 'SystemOwner:Logout' %}">Logout</a>
  <a href="{% url 'SystemOwner:EditView' %}">Edit Profile</a>
  <a href="/User/About/">About Us</a>
</div>

<div style="overflow:auto">
  <div class="menu">
    <div class="menuitem1">Menu</div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:LabView' %}">Home</a></div>
    <!--<div class="menuitem"><a class="a1" href="{% url 'SystemOwner:ProvideAccess' %}">Provide Access</a></div>-->
  </div>

  <div class="main">
    <div class="system">
    <h2>About Us</h2>  
    </div>
	<p style="text-align: justify; padding-left: 30px; padding-right: 30px">
	The objective of the Solar PV System Performance Evaluation project is to create a common platform 
	that would enable PV System Owners, Investors, Certification Bodies and other solar industry-related 
	users to access and upload information about photovoltaic systems. 
	The features of the application have been developed based on the requirements 
	primarily gathered from industry standards documents, interviews and research papers. 
	By providing users with useful and efficient features to exchange and access data about PV systems, 
	the application aims to simplify the tedious processes like performance evaluation and certification of PV Systems. 
	</p>
	<h2>PSP Team</h2>
	<h3>Project Mentor</h3>
	<div>
	<h4>Joseph Kuitche</h4>
	Lecturer<br>
	Information Technology Program<br>
	Arizona State University, Polytechnic Campus
	</div>
	<h4>Members</h4>
	<br>
	<div>
	<h4>Anirban Bhattacharya </h4>
	M.S. Information Technology<br>
	Tempe, Arizona
	</div>
	<div>
	<h4>Rasika Chafekar </h4>
	M.S. Information Technology<br>
	Tempe, Arizona
	</div>
	<div>
	<h4>Ruchira Dorsatwar </h4>
	M.S. Information Technology<br>
	Scotttsdale, Arizona
	</div>
	<div>
	<h4>Dinaker Prakash Kolipaka</h4>
	M.S. Information Technology<br>
	Tempe, Arizona
	</div>
	<div>
	<h4>Nischal Kumar </h4>
	M.S. Information Technology<br>
	Tempe, Arizona
	</div>
	<div>
	<h4>Aidan Payne </h4>
	M.S. Information Technology<br>
	Mesa, Arizona
	</div>
	<div>
	<h4>Alok Sahu</h4>
	M.S. Information Technology<br>
	Scottsdale, Arizona
	</div>
	<div>
	<h4>Anusha Samala</h4>
	M.S. Information Technology<br>
	Tempe, Arizona
	</div>
	<div>
	<h4>Krishna Deepika Villa</h4>
	M.S. Information Technology<br>
	Tempe, Arizona
	</div>
	
  </div>

</div>

</body>
</html>

PVSystem/templates/PVsystem.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static "css/PVsystem.css" %}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="font-family:Verdana;color:#aaaaaa;">

<div class="header" >
  <h1><img class="himg" src="{% static "images/asu.png" %}">PV Module Performance Evaluation System</h1>
</div>

<div class="topnav">
  <a href="{% url 'SystemOwner:Logout' %}">Logout</a>
  <a href="{% url 'SystemOwner:EditView' %}">Edit Profile</a>
  <a href="/User/About/">About Us</a>
</div>

<div style="overflow:auto">
  <div class="menu">
    <div class="menuitem1">Menu</div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Owner' %}">Home</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:InsertView' %}">Add New PV System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Update' %}">Update System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Delete' %}">Delete PV System</a></div>
    <!--<div class="menuitem"><a class="a1" href="{% url 'SystemOwner:ProvideAccess' %}">Provide Access</a></div>-->
	</div>

  <div class="main">
    <h3>PV System Details</h3>
    <div class="system">
      <ul>
          <li>System ID     : {{ key.0 }}</li>
          <li>Power Rating  : {{ key.2 }}</li>
          <li>Module Type   : {{ key.3 }}</li>
          <li>Array Type    : {{ key.4 }}</li>
          <li>ASYstem Loss  : {{ key.5 }}</li>
          <li>Tilt          : {{ key.6 }}</li>
          <li>System Type   : {{ key.7 }}</li>
      </ul>
        <button class="w3-button w3-green w3-small w3-round-large"><a href="{% url 'SystemOwner:Owner' %}">Go Back</a></button>
    </div>
  </div>


</div>



</body>
</html>

PVSystem/templates/UploadResultCSV.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static "css/UploadResultCsv.css" %}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="font-family:Verdana;color:#aaaaaa;">

<div class="header" >
  <h1><img class="himg" src="{% static "images/asu.png" %}">PV Module Performance Evaluation System</h1>
</div>

<div class="topnav">
  <a href="{% url 'SystemOwner:Logout' %}">Logout</a>
  <a href="{% url 'SystemOwner:EditView' %}">Edit Profile</a>
  <a href="/User/About/">About Us</a>
</div>

<div style="overflow:auto">

  <div class="main">
    <div class="system">
      <h3>Upload the CSV file</h3>
        {% if key == 1 %}
    		<h6>You have already uploaded Results for this System. If you want to update Re-upload.</h6>
  		{% endif %}
      <div class="form">

        <form action="/SystemOwner/ActualE/" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <label class="label1">Actual Results CSV File</label>
          <input type="file" name="csv_file" placeholder="Select the CSV file" required>

          <input type="submit" value="Upload">
          <button class="w3-button w3-green w3-small w3-round-large"><a href="{% url 'SystemOwner:LabView' %}">Go Back</a></button>
        </form>

      </div>
    </div>
  </div>

</div>

</body>
</html>

PVSystem/templates/details.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <ul>
      {% for a in key %}
        <li>{{ a }}</li>
      {% endfor %}
    </ul>
    <input type=button value="Go Back" class="btn btn-primary"onClick="javascript:history.go(-1);">
  </div>
{% endblock %}

PVSystem/templates/editprofile.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static "css/EditProfile.css" %}"/>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

</head>
<body style="font-family:Verdana;color:#aaaaaa;">

<div class="header">
  <h1><img class="himg" src="{% static "images/asu.png" %}">PV Module Performance Evaluation System</h1>
</div>

<div class="topnav">
  <a href="{% url 'SystemOwner:Logout' %}">Logout</a>
  <a href="/User/About/">About Us</a>
</div>

<div style="overflow:auto">
<div class="menu">
	<div class="menuitem1">Menu</div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Owner' %}">Home</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:InsertView' %}">Add New PV System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Update' %}">Update System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Delete' %}">Delete PV System</a></div>
    <!--<div class="menuitem"><a class="a1" href="{% url 'SystemOwner:ProvideAccess' %}">Provide Access</a></div>-->
</div>
<div class="main">
    <div class="system">
	<!--{% if key == 1 %}
    <h6>Details Saved Successfully!</h6>
	{% endif %}
	-->
      <h3>Edit Profile</h3>
      <div class="form">
        <div class="text">Enter Below Details to Edit your Profile</div>
        <br>
  
		<form action="javascript:alert('This feature is still under development');">
		{% csrf_token %}

		  <label for="fname" class="label1">First Name</label>
		  <input type="text" id="fname" name="firstname" placeholder="Enter first name.." value={{ key.0 }}>

		  <label for="lname" class="label1">Last Name</label>
		  <input type="text" id="lname" name="lastname" placeholder="Your last name.." value={{ key.1 }}>

		  <label for="email" class="label1">Email</label>
		  <input type="email" id="email" name="emailid" placeholder="Your Email id.." value={{ key.2 }}>

		  <label for="phone" class="label1">Contact Number</label>
		  <input type="number" id="phone" name="phone" placeholder="Your Contact Number.." value={{ key.3 }}>

		  <label for="country" class="label1">Address Line 1</label>
		  <input type="text" id="address1" name="address1" placeholder="Enter Address Line 1.." value={{ key.4 }}>
		  
		  <label for="country" class="label1">Address Line 2</label>
		  <input type="text" id="address2" name="address2" placeholder="Enter Address Line 2.." value={{ key.5 }}>
		  
		  <label for="country" class="label1">City</label>
		  <input type="text" id="city" name="city" placeholder="Enter City.." value={{ key.6 }}>
		  
		  <label for="country" class="label1">State</label>
		  <input type="text" id="state" name="state" placeholder="Enter State.." value={{ key.7 }}>
		  
		  <label for="country" class="label1">Zip</label>
		  <input type="number" id="zip" name="zip" placeholder="Enter Zip.." value={{ key.8 }}>
		  
		  <label for="password" class="label1">Password</label>
		  <input type="password" id="psw" name="password" placeholder="Enter Password.." value={{ key.9 }}>

		<input type="submit" value="Update Profile">
		</form>
		</div>
    </div>
  </div>
</div>
</body>

</html>

PVSystem/templates/expected_1.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <ul>
      {% for a in key %}
        {{ a }}
      {% endfor %}
    </ul>
    <input type=button value="Go Back" class="btn btn-primary"onClick="javascript:history.go(-1);">
  </div>
{% endblock %}

PVSystem/templates/expectedview.html
<!DOCTYPE html>
{% load staticfiles %}
{% block body_block %}
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "css/AddNewPVSystem.css" %}">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="font-family:Verdana;color:#aaaaaa;">
	
<div class="header" >
	<h1><img class="himg" src="{% static "images/asu.png" %}">PV Module Performance Evaluation System</h1>
</div>

<div class="topnav">
	<a href="{% url 'SystemOwner:Logout' %}">Logout</a>
	<a href="UpdateProfile.html">Edit Profile</a>
	<a href="/User/About/">About Us</a>
</div>
<div style="overflow:auto">
	<div class="menu">
    <div class="menuitem1">Menu</div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Owner' %}">Home</a></div>
    <div class="menuitem"><a class="a1" href="AddNewPVSystem.html">Add New PV System</a></div>
    <div class="menuitem"><a class="a1" href="{% url 'SystemOwner:Update' %}">Update System</a></div>
    <div class="menuitem"><a class="a1" href="DeleteSystem.html">Delete PV System</a></div>
    <!--<div class="menuitem"><a class="a1" href="{% url 'SystemOwner:ProvideAccess' %}">Provide Access</a></div>-->
</div>

<div class="jumbotron">
    <h3>Expected energy calculation</h3>
	<!-- <br/><br/><br/>	 -->
	<table class="table table-striped" align="center">
		<thead>
			<tr>
				<th>Month</th>
				<th>Energy Value</th>
			</tr>
		</thead>
		<tbody>
		<tr>
			<td>January</td>
			<td>{{ key.0 }}</td>
		</tr>
		<tr>
			<td>February</td>
			<td>{{ key.1 }}</td>
		</tr>
		<tr>
			<td>March</td>
			<td>{{ key.2 }}</td>
		</tr>
		<tr>
			<td>April</td>
			<td>{{ key.3 }}</td>
		</tr>
		<tr>
			<td>May</td>
			<td>{{ key.4 }}</td>
		</tr>
		<tr>
			<td>June</td>
			<td>{{ key.5 }}</td>
		</tr>
		<tr>
			<td>July</td>
			<td>{{ key.6 }}</td>
		</tr>
		<tr>
			<td>August</td>
			<td>{{ key.7 }}</td>
		</tr>
		<tr>
			<td>September</td>
			<td>{{ key.8 }}</td>
		</tr>
		<tr>
			<td>October</td>
			<td>{{ key.9 }}</td>
		</tr>
		<tr>
			<td>November</td>
			<td>{{ key.10 }}</td>
		</tr>
		<tr>
			<td>December</td>
			<td>{{ key.11 }}</td>
		</tr>
		</tbody>
	</table>
	<!--<input type=button value="Go Back" class="btn btn-primary"onClick="javascript:history.go(-1);">-->
</div>
</br>
<button class="w3-button w3-green w3-small w3-round-large"><a href = "{% url 'SystemOwner:Owner' %}">Go Back</a></button>
    	
<!--
    <form action="/SystemOwner/DownloadPredResults/" method="POST">
        {% csrf_token %}
        <label class="label1">Download XML File</label>
        <input type="submit" value="Download Results">

    </form>

-->
</div>
</body>
</html>

{% endblock %}

PVSystem/templates/index_1.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <ol>
      {% for list in key %}
            <li><a href="{% url 'SystemOwner:Details' list.0 %} ">System {{ list.0 }}</a>
            <button type="submit" class="btn btn-success"><a href="{% url 'SystemOwner:EE' list.0 %} ">Calculate EE</a></button>
            <button type="submit" class="btn btn-success"><a href="{% url 'SystemOwner:PE' list.0 %} ">Calculate PE</a></button></li>
      {% endfor %}
    </ol>
      <button type="submit" name="button"><a href="#"></a>Submit</button>
  </div>
{% endblock %}